version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: MySQL-container
    ports:
      - "3307:3306"
    environment:
      DB_NAME: book_crud
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: Go-Book-Crud
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_NAME: book_crud
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
    volumes:
      - ./cmd:/BookCrud_App/cmd  

volumes:
  db_data:
